name: Pytest

on:
  push:
  schedule:
    - cron: '0 2 * * 1' # The task runs at 2 a.m. every Monday.

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]
    name: Python ${{ matrix.python-version }} ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: test-env
          channels: bioconda, conda-forge, defaults, anaconda

      - name: Install dependencies
        run: |
          conda install -c bioconda bowtie pytest numpy pandas primer3-py -y
          # python -m pip install --upgrade pip pytest numpy pandas primer3-py

      - name: Run pytest on Linux🐧, macOS🍎
        env:
          PYTHONPATH: src
        run: |
          python -m pytest tests -p no:warnings -vv
